// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        //jcenter()
        google()
        mavenCentral()
        gradlePluginPortal() // <--- ADD THIS: Necessary to find the plugin
    }
    dependencies {
        // AGP 9.1.0 is fine, but it's very strict
        classpath 'com.android.tools.build:gradle:9.1.1'

        // Bump this to the latest 2.9.7 to support AGP 9 APIs
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.9.8'

        // Add these lines so the plugins are available for your modules
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10'
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal() // <--- ADD THIS: Necessary to find the plugin
    }
}
