pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// 1. Apply the Foojay resolver plugin
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

// 2. Configure toolchain management
rootProject.name = "OpenSongTablet"

include ':app'
include ':wear'

// This ensures Gradle looks in the correct folders
project(':app').projectDir = new File(settingsDir, 'app')
project(':wear').projectDir = new File(settingsDir, 'wear')