plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace = 'com.garethevans.church.opensongtablet.wear'
    compileSdk 35

    defaultConfig {
        applicationId = "com.garethevans.church.opensongtablet"
        minSdk 23
        targetSdk 35
        versionCode 442     // MATCH the mobile version
        versionName "6.7.1" // MATCH the mobile version
    }

    flavorDimensions "distribution"
    productFlavors {
        withWear {
            dimension "distribution"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    buildFeatures {
        compose = true
    }
}

repositories {
    google()
    mavenCentral()
    maven {
        url = "https://jitpack.io"
    }
}

dependencies {

    implementation 'com.google.android.gms:play-services-wearable:19.0.0'
    implementation platform('androidx.compose:compose-bom:2026.02.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.wear.compose:compose-material:1.5.6'
    implementation 'androidx.wear.compose:compose-foundation:1.5.6'
    implementation 'androidx.wear:wear-tooling-preview:1.0.0'
    implementation 'androidx.activity:activity-compose:1.12.4'
    implementation 'androidx.core:core-splashscreen:1.2.0'
}
