# This file is used to store login keys securely
# It is added to my github ignore file, so it isn't uploaded
# A basic file should be on GitHub, so forks don't crash.
# Logins requiring the info won't work though!!

# First up, OpenChords
openchordsusername=openchordsusername
openchordspassword=openchordspassword
openchordssalt=openchordssalt